# Site settings
title: BastionAI
description: >-
  BastionAI creates products oriented to leverage the power of local models 
  focusing on privacy, security, and innovation.
baseurl: ""
url: "https://bastionai.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: BastionAI
logo: /assets/images/logo.png
social:
  name: BastionAI
  links:
    - https://github.com/bastionai

# Google Tag Manager
google_tag_manager: "GTM-NJS6SDGJ"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Products"
    url: "/products/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

header_pages:
  - index.md
  - products.md
  - about.md
  - contact.md

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 