# Site settings
title: BastionAI
description: >-
  BastionAI creates products oriented to leverage the power of local models 
  focusing on privacy, security, and innovation.
baseurl: ""
url: "https://bastionai.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: BastionAI
logo: /assets/images/logo.png
social:
  name: BastionAI
  links:
    - https://github.com/bastionai

# Navigation
header_pages:
  - index.md
  - products.md
  - about.md
  - contact.md

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 